/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek.gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import proyek.organize.Catalog;
import proyek.organize.Products;

/**
 *
 * @author Reyhan
 */
public class FrameApp extends javax.swing.JFrame {

    private static final String FILE_PRODUCTS = "src\\proyek\\notes\\products.xlsx";
    private static final String FILE_LOG = "src\\proyek\\notes\\log.xlsx";
    private Catalog catalog;
    public DashboardPanel dashPanel;
    public OrganizeItemsPanel OIPanel;
    private StatisticsPanel statPanel;
    private TransactionPanel transPanel;
    private PopUpAddNewItem popUpNew;
    private PopUpOIPanel popUpEdit;
    private Login loginPanel;

    /**
     * Creates new form FrameApp
     *
     * @throws java.io.IOException
     */
    public FrameApp() throws IOException {
        statPanel = new StatisticsPanel();
        dashPanel = new DashboardPanel();
        OIPanel = new OrganizeItemsPanel();
        transPanel = new TransactionPanel();
        popUpNew = new PopUpAddNewItem();
        popUpEdit = new PopUpOIPanel();
        catalog = new Catalog();
        collectProducts();
        try {
            logLastItem();
        } catch (Exception e) {
            
        }  
        initComponents();
//        jPanelSignIn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPanelForeground = new javax.swing.JPanel();
        jPanelDashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTransaction = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelStatistics = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelOI = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelSignIn = new javax.swing.JPanel();
        jLabelSignIn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBackground.setBackground(new java.awt.Color(52, 73, 94));

        jPanelForeground.setBackground(new java.awt.Color(52, 73, 94));

        jPanelDashboard.setBackground(new java.awt.Color(52, 73, 94));
        jPanelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDashboardMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek/icons/dashboard.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanelTransaction.setBackground(new java.awt.Color(52, 73, 94));
        jPanelTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTransactionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTransactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTransactionMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek/icons/transaction (1)_1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transaction");

        javax.swing.GroupLayout jPanelTransactionLayout = new javax.swing.GroupLayout(jPanelTransaction);
        jPanelTransaction.setLayout(jPanelTransactionLayout);
        jPanelTransactionLayout.setHorizontalGroup(
            jPanelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransactionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTransactionLayout.setVerticalGroup(
            jPanelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTransactionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jPanelStatistics.setBackground(new java.awt.Color(52, 73, 94));
        jPanelStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStatisticsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelStatisticsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelStatisticsMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek/icons/line-chart.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Statistics");

        javax.swing.GroupLayout jPanelStatisticsLayout = new javax.swing.GroupLayout(jPanelStatistics);
        jPanelStatistics.setLayout(jPanelStatisticsLayout);
        jPanelStatisticsLayout.setHorizontalGroup(
            jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatisticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStatisticsLayout.setVerticalGroup(
            jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatisticsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jPanelOI.setBackground(new java.awt.Color(52, 73, 94));
        jPanelOI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelOIMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelOIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelOIMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek/icons/delivery-packages-on-a-trolley.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Organize Items");

        javax.swing.GroupLayout jPanelOILayout = new javax.swing.GroupLayout(jPanelOI);
        jPanelOI.setLayout(jPanelOILayout);
        jPanelOILayout.setHorizontalGroup(
            jPanelOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOILayout.setVerticalGroup(
            jPanelOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Made by students of");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Software Engineering");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek/icons/Webp.net-resizeimage (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel9)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSignIn.setBackground(new java.awt.Color(52, 73, 94));
        jPanelSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSignInMouseExited(evt);
            }
        });

        jLabelSignIn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelSignIn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek/icons/logout.png"))); // NOI18N
        jLabelSignIn.setText("  Log Out");
        jLabelSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSignInMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSignInLayout = new javax.swing.GroupLayout(jPanelSignIn);
        jPanelSignIn.setLayout(jPanelSignInLayout);
        jPanelSignInLayout.setHorizontalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignInLayout.setVerticalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jLabel13.setFont(new java.awt.Font("Arvo", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SM4");

        jLabel14.setFont(new java.awt.Font("Arvo", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(129, 207, 224));
        jLabel14.setText("Store Manager");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13))
                    .addComponent(jLabel14))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelForegroundLayout = new javax.swing.GroupLayout(jPanelForeground);
        jPanelForeground.setLayout(jPanelForegroundLayout);
        jPanelForegroundLayout.setHorizontalGroup(
            jPanelForegroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelOI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelForegroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelForegroundLayout.setVerticalGroup(
            jPanelForegroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForegroundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelContainer.setBackground(new java.awt.Color(66, 134, 244));
        jPanelContainer.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabel11.setText("Welcome to Dodolan!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel11)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel11)
                .addContainerGap(514, Short.MAX_VALUE))
        );

        jPanelContainer.add(jPanel3, "card2");

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addComponent(jPanelForeground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelForeground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDashboardMouseEntered
        setPanelColor(jPanelDashboard, "Dashboard - SM4 Store Manager");
        
    }//GEN-LAST:event_jPanelDashboardMouseEntered

    private void jPanelDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDashboardMouseExited
        if (!dashPanel.isShowing()) {
            resetPanelColor(jPanelDashboard);
        }
    }//GEN-LAST:event_jPanelDashboardMouseExited

    private void jPanelTransactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTransactionMouseEntered
        setPanelColor(jPanelTransaction, "Transaction - SM4 Store Manager");
        transPanel.setCatalogProducts(catalog);
        transPanel.showProducts();
    }//GEN-LAST:event_jPanelTransactionMouseEntered

    private void jPanelTransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTransactionMouseExited
        if (!transPanel.isShowing()) {
            catalog = transPanel.getCatalogProducts();
            resetPanelColor(jPanelTransaction);
        }
    }//GEN-LAST:event_jPanelTransactionMouseExited

    private void jPanelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDashboardMouseClicked
        setPanel(jPanelDashboard, dashPanel);
        try {            
            logLastItem();
//            if (OIPanel.getPopUpAdd() != null || OIPanel.getPopUpEdit() != null) {
//                if (OIPanel.getChoice() == '1') {
//                    dashPanel.setLastItemAdded(OIPanel.getPopUpEdit().getProduct());
//                    OIPanel.setChoice('0');
//                } else if (OIPanel.getPopUpAdd().isSuccess()){
//                    dashPanel.setLastItemAdded(OIPanel.getPopUpAdd().getLastAdded());
//                    OIPanel.getPopUpAdd().setSuccess(false);
//                }
//            }
//            dashPanel.setLastItemDeleted(OIPanel.getLastItem());
            dashPanel.setLastItemDeleted(OIPanel.getLastItem());
            dashPanel.setLastItemAdded();
            dashPanel.setLastItemDeleted();
        } catch (IOException ex) {
            Logger.getLogger(FrameApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanelDashboardMouseClicked

    private void jPanelOIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelOIMouseEntered
        setPanelColor(jPanelOI, "Organize Items - SM4 Store Manager");
        OIPanel.setCatalogProducts(catalog);
        OIPanel.ShowProducts();
    }//GEN-LAST:event_jPanelOIMouseEntered

    private void jPanelOIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelOIMouseExited
        if (!OIPanel.isShowing()) {
//            if (OIPanel.getChoice() == '3') {
//                dashPanel.setLastItemAdded(OIPanel.getPopUpAdd().getNewProduct());
//            } else {
//                dashPanel.setLastItemAdded(OIPanel.getPopUpEdit().getProduct());
//            }
//            dashPanel.setLastItemDeleted(OIPanel.getLastItem());
            catalog = OIPanel.getCatalogProducts();
//            writeExcel();
            resetPanelColor(jPanelOI);
        }
    }//GEN-LAST:event_jPanelOIMouseExited

    private void jPanelOIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelOIMouseClicked
        setPanel(jPanelOI, OIPanel);
        OIPanel.getPopUpAdd().setFA(this);
//        if (OIPanel.getChoice() == '3') {
//            dashPanel.setLastItemAdded(OIPanel.getPopUpAdd().getNewProduct());
//        } else {
//            dashPanel.setLastItemAdded(OIPanel.getPopUpEdit().getProduct());
//        }
//        dashPanel.setLastItemDeleted(OIPanel.getLastItem());
//        catalog = OIPanel.getCatalogProducts();
//        OIPanel.setCatalogProducts(catalog);
        OIPanel.ShowProducts();
    }//GEN-LAST:event_jPanelOIMouseClicked

    public void jPanelMouseClicked(MouseEvent evt) {
        jPanelOIMouseClicked(evt);
    }

    private void jPanelTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTransactionMouseClicked
        setPanel(jPanelTransaction, transPanel);
    }//GEN-LAST:event_jPanelTransactionMouseClicked

    private void jPanelStatisticsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStatisticsMouseEntered
        // TODO add your handling code here:
        setPanelColor(jPanelStatistics, "Statistics - SM4 Store Manager");
    }//GEN-LAST:event_jPanelStatisticsMouseEntered

    private void jPanelStatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStatisticsMouseClicked
        // TODO add your handling code here:
        setPanel(jPanelStatistics, statPanel);
    }//GEN-LAST:event_jPanelStatisticsMouseClicked

    private void jPanelStatisticsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStatisticsMouseExited
        // TODO add your handling code here:
        if (!statPanel.isShowing()) {
            resetPanelColor(jPanelStatistics);
        }
    }//GEN-LAST:event_jPanelStatisticsMouseExited

    private void jLabelSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignInMouseClicked
        
    }//GEN-LAST:event_jLabelSignInMouseClicked

    private void jLabelSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignInMouseEntered
        
    }//GEN-LAST:event_jLabelSignInMouseEntered

    private void jLabelSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignInMouseExited
        
    }//GEN-LAST:event_jLabelSignInMouseExited

    private void jPanelSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSignInMouseClicked
        try {
            loginPanel = new Login();
        } catch (IOException ex) {
            Logger.getLogger(FrameApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK, false);
        this.setVisible(false);
        loginPanel.setVisible(true);
    }//GEN-LAST:event_jPanelSignInMouseClicked

    private void jPanelSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSignInMouseEntered
        setPanelColor(jPanelSignIn, "Login - SM4 Store Manager");
    }//GEN-LAST:event_jPanelSignInMouseEntered

    private void jPanelSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSignInMouseExited
        resetPanelColor(jPanelSignIn);
    }//GEN-LAST:event_jPanelSignInMouseExited

    void setPanel(JPanel panelParent, JPanel panel) {
        resetAllPanelColor(panelParent);
        jPanelContainer.removeAll();
        jPanelContainer.add(panel);
        jPanelContainer.repaint();
        jPanelContainer.revalidate();
        jPanelSignIn.setVisible(true);
    }

    void resetAllPanelColor(JPanel panel) {
        resetPanelColor(jPanelDashboard);
        resetPanelColor(jPanelTransaction);
        resetPanelColor(jPanelStatistics);
        resetPanelColor(jPanelOI);
        setPanelColor(panel, null);
    }

    void setPanelColor(JPanel panel, String title) {
        panel.setBackground(new Color(1, 50, 67));
        this.setTitle(title);
    }

    void resetPanelColor(JPanel panel) {
        panel.setBackground(new Color(52,73,94));
    }

    public void logLastItem() throws IOException {
        FileInputStream fileProducts = new FileInputStream(new File(FILE_LOG));
        Workbook workbook = new XSSFWorkbook(fileProducts);
        Sheet spreadsheet = workbook.getSheetAt(1);
        Iterator<Row> rowIterator = spreadsheet.iterator();
//        Row currentRow = rowIterator.next();
        Row currentRow;
        Cell currentCell = null;
        Products lastProducts = null;
        String current = null;

        while (rowIterator.hasNext()) {
            currentRow = rowIterator.next();
            Iterator<Cell> cellIterator = currentRow.cellIterator();
            int indeks = 0;
            lastProducts = new Products();

            while (cellIterator.hasNext()) {
                int indeksForProducts = indeks;
                currentCell = cellIterator.next();
                if (currentCell.getCellTypeEnum() == CellType.STRING) {
                    if (indeksForProducts == 0) {
                        lastProducts.setProductCode(currentCell.getStringCellValue());
                        System.out.println(lastProducts.getProductCode());
                    } else if (indeksForProducts == 1) {
                        lastProducts.setProductName(currentCell.getStringCellValue());
                        System.out.println(lastProducts.getProductName());
                    } else if (indeksForProducts == 2) {
                        lastProducts.setProductCategory(currentCell.getStringCellValue());
                        System.out.println(lastProducts.getProductCategory());
                    } else if (indeksForProducts == 6) {
                        current = String.valueOf(currentCell.getStringCellValue());
                        System.out.println(current);
                    }
                } else if (currentCell.getCellTypeEnum() == CellType.NUMERIC) {
                    if (indeksForProducts == 3) {
                        lastProducts.setSalePrice((int) currentCell.getNumericCellValue());
                        System.out.println(lastProducts.getSalePrice());
                    } else if (indeksForProducts == 4) {
                        lastProducts.setProductStock((int) currentCell.getNumericCellValue());
                        System.out.println(lastProducts.getProductStock());
                    } else if (indeksForProducts == 5) {
                        lastProducts.setBuyItemPrice((int) currentCell.getNumericCellValue());
                        System.out.println(lastProducts.getBuyItemPrice());
                    }
                }
                indeks++;
            }
            if (current.equals("Last Added")) {
                dashPanel.setLastItemAdded(lastProducts);
            } else if (current.equals("Last Deleted")) {
                dashPanel.setLastItemDeleted(lastProducts);
            }
        }
    }

    void collectProducts() throws IOException {
        FileInputStream fileProducts = new FileInputStream(new File(FILE_PRODUCTS));
        Workbook workbook = new XSSFWorkbook(fileProducts);
        Sheet spreadsheet = workbook.getSheetAt(0);
        Iterator<Row> rowIterator = spreadsheet.iterator();
        Row currentRow = rowIterator.next();

        List<Products> listProducts = new ArrayList<>();
        Products tmpProducts = null;

        while (rowIterator.hasNext()) {
            currentRow = rowIterator.next();
            Iterator<Cell> cellIterator = currentRow.cellIterator();
            int indeks = 0;
            tmpProducts = new Products();

            while (cellIterator.hasNext()) {
                int indeksForProducts = indeks;
                Cell currentCell = cellIterator.next();
                if (currentCell.getCellTypeEnum() == CellType.STRING) {
                    if (indeksForProducts == 0) {
                        tmpProducts.setProductCode(currentCell.getStringCellValue());
                    } else if (indeksForProducts == 1) {
                        tmpProducts.setProductName(currentCell.getStringCellValue());
                    } else if (indeksForProducts == 2) {
                        tmpProducts.setProductCategory(currentCell.getStringCellValue());
                    }
                } else if (currentCell.getCellTypeEnum() == CellType.NUMERIC) {
                    if (indeksForProducts == 3) {
                        tmpProducts.setSalePrice((int) currentCell.getNumericCellValue());
                    } else if (indeksForProducts == 4) {
                        tmpProducts.setProductStock((int) currentCell.getNumericCellValue());
                    } else if (indeksForProducts == 5) {
                        tmpProducts.setBuyItemPrice((int) currentCell.getNumericCellValue());
                    }
                }
                indeks++;
            }
            listProducts.add(tmpProducts);
        }
        catalog.setProducts(listProducts);
    }
//     /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameApp().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSignIn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelContainer;
    public javax.swing.JPanel jPanelDashboard;
    private javax.swing.JPanel jPanelForeground;
    public javax.swing.JPanel jPanelOI;
    public javax.swing.JPanel jPanelSignIn;
    private javax.swing.JPanel jPanelStatistics;
    private javax.swing.JPanel jPanelTransaction;
    // End of variables declaration//GEN-END:variables

    /**
     * @param catalog the catalog to set
     */
    public void setCatalog(Catalog catalog) {
        this.catalog = catalog;
    }
}
