/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek.gui;

import java.awt.Color;
import java.awt.Frame;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import proyek.login.Staff;

/**
 *
 * @author Reyhan
 */
public class Login extends javax.swing.JFrame {
    
    private List<Staff> members = new ArrayList<>();
    private static final String FILE_MEMBER = "src\\proyek\\notes\\MEM.xlsx";
    private FrameApp appGui;
    
    /**
     * Creates new form Login
     */
    public Login() throws IOException {
        appGui = new FrameApp();
        fetchData(FILE_MEMBER);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogBackgorund = new javax.swing.JPanel();
        jPanelLogForeground = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelLogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogBackgorund.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLogBackgorund.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogForeground.setBackground(new java.awt.Color(52, 73, 94));
        jPanelLogForeground.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLogForeground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsername.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jPanelLogForeground.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 30));

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanelLogForeground.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanelLogForeground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, 10));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanelLogForeground.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 10));

        jPanelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelLoginMouseExited(evt);
            }
        });

        jLabel4.setText("Login");

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel4)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanelLogForeground.add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 190, 40));

        jPanelLogBackgorund.add(jPanelLogForeground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 380));

        jLabel13.setFont(new java.awt.Font("Arvo", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(52, 73, 94));
        jLabel13.setText("SM4");
        jPanelLogBackgorund.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arvo", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(129, 207, 224));
        jLabel14.setText("Store Manager");
        jPanelLogBackgorund.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        getContentPane().add(jPanelLogBackgorund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jPanelLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLoginMouseEntered
        setPanelColor(jPanelLogin);
    }//GEN-LAST:event_jPanelLoginMouseEntered

    private void jPanelLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLoginMouseExited
        resetPanelColor(jPanelLogin);
    }//GEN-LAST:event_jPanelLoginMouseExited

    private void jPanelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLoginMouseClicked
        String username = this.jTextFieldUsername.getText();
        char[] password = this.jPasswordField.getPassword();
        String pass = new String(password);
        System.out.println(pass);
        Iterator<Staff> memberIterator = this.members.iterator(); Staff currMember = new Staff();
        boolean valid = false;
        
        if(!username.equals(null) && !pass.equals(null)) {    
            while(memberIterator.hasNext()) {
                currMember = memberIterator.next();
                if(currMember.getUsername().equals(username))
                    if(currMember.getPassword().equals(pass))
                        valid = true;
            }   
        }
        if(valid) {
            this.setVisible(false);
            this.appGui.setExtendedState(Frame.MAXIMIZED_BOTH);
            this.appGui.setPanel(appGui.jPanelDashboard, appGui.dashPanel);
             try {            
            this.appGui.logLastItem();
//            if (OIPanel.getPopUpAdd() != null || OIPanel.getPopUpEdit() != null) {
//                if (OIPanel.getChoice() == '1') {
//                    dashPanel.setLastItemAdded(OIPanel.getPopUpEdit().getProduct());
//                    OIPanel.setChoice('0');
//                } else if (OIPanel.getPopUpAdd().isSuccess()){
//                    dashPanel.setLastItemAdded(OIPanel.getPopUpAdd().getLastAdded());
//                    OIPanel.getPopUpAdd().setSuccess(false);
//                }
//            }
//            dashPanel.setLastItemDeleted(OIPanel.getLastItem());
//            this.appGui.dashPanel.setLastItemDeleted(this.appGui.OIPanel.getLastItem());
            this.appGui.dashPanel.setLastItemAdded();
            this.appGui.dashPanel.setLastItemDeleted();
        } catch (IOException ex) {
            Logger.getLogger(FrameApp.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.appGui.setVisible(true);
        }
        else JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
    }//GEN-LAST:event_jPanelLoginMouseClicked

    void setPanelColor(JPanel panel) {
        panel.setBackground(Color.LIGHT_GRAY);
    }

    void resetPanelColor(JPanel panel) {
        panel.setBackground(new Color(255, 255, 255));
    }
    
    void fetchData(String fileName) throws FileNotFoundException, IOException {
        Staff member = new Staff();
        int index = 0;
        Row currentRow;
        Cell currentCell;
        FileInputStream file = new FileInputStream(new File(fileName));
        Workbook workbook = new XSSFWorkbook(file);
        Sheet sheet = workbook.getSheetAt(0);
        Iterator<Row> rowIterator = sheet.iterator();
        
        while(rowIterator.hasNext()) {
            member = new Staff();
            currentRow = rowIterator.next();
            Iterator<Cell> cellIterator = currentRow.iterator();
            index = 0;
            
            while(cellIterator.hasNext()) {
                currentCell = cellIterator.next();
                
//                System.out.println("ini index : " + index);
                
                if(currentCell.getCellTypeEnum() == CellType.STRING) {
                    if(index == 0) {
                        member.setUsername(currentCell.getStringCellValue());
//                        System.out.println("ini username: " + member.getUsername());
                    }
                    else if(index == 1) {
                        member.setPassword(currentCell.getStringCellValue());
//                        System.out.println("ini password: " + member.getPassword());
                    }
                } else {
                    currentCell.setCellType(CellType.STRING);
                    member.setPassword(currentCell.getStringCellValue());
//                    System.out.println("ini password(NUM): " + member.getPassword());
                }
                
                index++;
            }
            this.members.add(member);
        }
    }

    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelLogBackgorund;
    private javax.swing.JPanel jPanelLogForeground;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
